
export const blockDefinitions = [
    { name: "[00] Blank", type: 0, isOriented: false, isTextured: false },
    { name: "[01] Stone", type: 0, isOriented: false, isTextured: false },
    { name: "[02] Brick", type: 0, isOriented: false, isTextured: false },
    { name: "[03] Waterless Stone", type: 0, isOriented: false, isTextured: false },
    { name: "[04] Win", type: 0, isOriented: false, isTextured: false },
    { name: "[05] Stair", type: 1, isOriented: true, isTextured: false },
    { name: "[06] Bin", type: 0, isOriented: false, isTextured: false },
    { name: "[07] Stone Wedge", type: 1, isOriented: true, isTextured: false },
    { name: "[08] Dirt Wedge", type: 1, isOriented: true, isTextured: false },
    { name: "[09] Yellow Ball", type: 0, isOriented: false, isTextured: false },
    { name: "[10] Fake Win", type: 1, isOriented: true, isTextured: false },
    { name: "[11] Water", type: 0, isOriented: false, isTextured: false },
    { name: "[12] Grass", type: 0, isOriented: false, isTextured: false },
    { name: "[13] Dark Pillar", type: 0, isOriented: false, isTextured: false },
    { name: "[14] Stone Rounded", type: 1, isOriented: true, isTextured: false },
    { name: "[15] Robot Tap To Walk (B)", type: 1, isOriented: true, isTextured: false },
    { name: "[16] Zapper", type: 1, isOriented: true, isTextured: false },
    { name: "[17] Draggable", type: 0, isOriented: false, isTextured: false },
    { name: "[18] Dirt From Grass", type: 0, isOriented: false, isTextured: false },
    { name: "[19] Wheel", type: 1, isOriented: true, isTextured: false },
    { name: "[20] Metal Stair", type: 1, isOriented: true, isTextured: false },
    { name: "[21] Metal Rounded", type: 1, isOriented: true, isTextured: false },
    { name: "[22] Motor", type: 1, isOriented: true, isTextured: false },
    { name: "[23] Engine Box", type: 0, isOriented: false, isTextured: false },
    { name: "[24] Stone", type: 0, isOriented: false, isTextured: false },
    { name: "[25] Metal", type: 0, isOriented: false, isTextured: false },
    { name: "[26] Robot Turns Right (R)", type: 1, isOriented: true, isTextured: false },
    { name: "[27] Eye", type: 0, isOriented: false, isTextured: false },
    { name: "[28] Hidden", type: 0, isOriented: false, isTextured: false },
    { name: "[29] Metal Stone With Orientation", type: 1, isOriented: true, isTextured: false },
    { name: "[30] Curve Rail", type: 1, isOriented: true, isTextured: false },
    { name: "[31] Metal Stone Pillar", type: 1, isOriented: true, isTextured: false },
    { name: "[32] Metal Half Pillar", type: 1, isOriented: true, isTextured: false },
    { name: "[33] Slider Rail", type: 1, isOriented: true, isTextured: false },
    { name: "[34] Stone Half Pillar", type: 1, isOriented: true, isTextured: false },
    { name: "[35] Stone Pillar", type: 1, isOriented: true, isTextured: false },
    { name: "[36] Draggable Pillar", type: 1, isOriented: true, isTextured: false },
    { name: "[37] Ball", type: 0, isOriented: false, isTextured: false },
    { name: "[38] Waterless Stone", type: 0, isOriented: false, isTextured: false },
    { name: "[39] Metal Pillar", type: 1, isOriented: true, isTextured: false },
    { name: "[40] Battery Box", type: 0, isOriented: false, isTextured: false },
    { name: "[41] Slider", type: 1, isOriented: true, isTextured: false },
    { name: "[42] Noisy Sound Box", type: 0, isOriented: false, isTextured: false },
    { name: "[43] Fence", type: 1, isOriented: true, isTextured: false },
    { name: "[44] Box (Undefined)", type: 0, isOriented: false, isTextured: false },
    { name: "[45] Theme Sound Box", type: 0, isOriented: false, isTextured: false },
    { name: "[46] Card Sound Box", type: 0, isOriented: false, isTextured: false },
    { name: "[47] Trigger", type: 0, isOriented: false, isTextured: false },
    { name: "[48] Box (Undefined)", type: 0, isOriented: false, isTextured: false },
    { name: "[49] Metal Wedge", type: 1, isOriented: true, isTextured: false },
    { name: "[50] Robot Turns Left (L)", type: 1, isOriented: true, isTextured: false },
    { name: "[51] Star", type: 0, isOriented: false, isTextured: false },
    { name: "[52] Dirt", type: 0, isOriented: false, isTextured: false },
    { name: "[53] Frame", type: 0, isOriented: false, isTextured: false },
    { name: "[54] Font OFF", type: 2, isOriented: false, isTextured: true },
    { name: "[55] Font ON", type: 2, isOriented: false, isTextured: true },
    { name: "[56] Font ON/OFF", type: 2, isOriented: false, isTextured: true },
    { name: "[57] Fake Motor (Stone-Brick)", type: 3, isOriented: true, isTextured: true },
    { name: "[58] Fake Motor (Grass-Fence)", type: 3, isOriented: true, isTextured: true },
    { name: "[59] Fake Motor (Dirt)", type: 3, isOriented: true, isTextured: true },
    { name: "[60] Fake Motor (Brick-Metal)", type: 3, isOriented: true, isTextured: true },
    { name: "[61] Wire", type: 1, isOriented: true, isTextured: false },
    { name: "[62] L Wire", type: 1, isOriented: true, isTextured: false },
    { name: "[63] T Wire", type: 1, isOriented: true, isTextured: false },
    { name: "[64] Font OFF", type: 2, isOriented: false, isTextured: true },
    { name: "[65] Fake Motor (R-L)", type: 3, isOriented: true, isTextured: true },
    { name: "[66] Font ON/OFF", type: 2, isOriented: false, isTextured: true },
    { name: "[67] Fake Motor (Zapper)", type: 3, isOriented: true, isTextured: true }
];

export const orientations = [
	"Up-Forward", "Up-Right", "Up-Back", "Up-Left", 
	"Forward-Down", "Right-Down", "Back-Down", "Left-Down", 
	"Down-Back", "Down-Left", "Down-Forward", "Down-Right", 
	"Back-Up", "Left-Up", "Forward-Up", "Right-Up", 
	"Left-Forward", "Forward-Right", "Right-Back", "Back-Left", 
	"Right-Forward", "Back-Right", "Left-Back", "Forward-Left"
];

export const fontTexture = Array.from({ length: 256 }, (_, i) => i);

